name: "gcm-test"
on: # rebuild any PRs and main branch changes
  push:
    branches:
      - update-for-homebrew-casks

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Homebrew deployment
      uses: ./
      with:
        token: ${{ secrets.HOMEBREW_TOKEN }}
        tap: ldennington/homebrew-casks
        branch: master
        name: git-credential-manager
        type: cask
        releaseRepo: 'ldennington/git-credential-manager'
        releaseTag: 'v45.54'
        releaseAsset: |
          gcm-osx-x64-(.*)\.pkg
          gcm-osx-arm64-(.*)\.pkg
        alwaysUsePullRequest: true
        message: |
          A test GCM release! :rocket:
